<a href="https://colab.research.google.com/github/notjayasurya/DeepLearning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Fundamental concepts of tensors**

In [22]:
import tensorflow as tf

import numpy as np
print(tf.__version__)

2.5.0


In [23]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [24]:
#Checking the no of dimensions of a tensor
scalar.ndim

0

In [25]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [26]:
vector.ndim

1

In [27]:
matrix = tf.constant([[24,48],[18,7]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[24 48]
 [18  7]], shape=(2, 2), dtype=int32)
2


In [28]:
#Creating another matrix
another_matrix = tf.constant([[10.,8.],
                             [1.,9.],
                             [10.,24.]],dtype=tf.float64)
print(another_matrix)
print(another_matrix.ndim)

tf.Tensor(
[[10.  8.]
 [ 1.  9.]
 [10. 24.]], shape=(3, 2), dtype=float64)
2


What we've created so far:
Scalar : a single number
vector : number with direction
matrix: a 2d array of numbers
Tensors : An n dim array of numbers .


### Creating tensors with 'tf.Variable'

In [29]:
changeable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changeable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [30]:
changeable_tensor[0].assign(18)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([18,  7], dtype=int32)>

In [31]:
# Creating Random tensors : Playback = 1:22:42

In [32]:
random_1 = tf.random.Generator.from_seed(36)
random_1 = random_1.normal(shape=(2,4))

random_2 = tf.random.Generator.from_seed(36)
random_2 = random_2.normal(shape = (2,4))

random_1,random_2, random_1 == random_2


(<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[-0.645002  ,  0.18022095, -0.14656258,  0.34374258],
        [ 0.41367555,  0.17573498, -1.0871261 ,  0.45905176]],
       dtype=float32)>, <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[-0.645002  ,  0.18022095, -0.14656258,  0.34374258],
        [ 0.41367555,  0.17573498, -1.0871261 ,  0.45905176]],
       dtype=float32)>, <tf.Tensor: shape=(2, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True]])>)

In [33]:
# Shuffling the order of tensors (valuable for shuffling the data)

In [34]:
not_shuffled = tf.constant([[10,7],
                            [24,7],
                           [18,45]],dtype=tf.int64)
print(not_shuffled.ndim)
not_shuffled

2


<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[10,  7],
       [24,  7],
       [18, 45]])>

In [35]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[10,  7],
       [18, 45],
       [24,  7]])>

In [36]:
tf.ones([4,8], dtype=tf.int32)

<tf.Tensor: shape=(4, 8), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>

In [37]:
#Converting numpy arrays into tensors

numpy_array = np.random.randint(10,50,20)
numpy_array


array([21, 48, 29, 23, 31, 15, 19, 27, 14, 29, 45, 30, 25, 33, 23, 10, 16,
       46, 49, 40])

In [38]:
A = tf.constant(numpy_array,shape =(5,4))
A

<tf.Tensor: shape=(5, 4), dtype=int64, numpy=
array([[21, 48, 29, 23],
       [31, 15, 19, 27],
       [14, 29, 45, 30],
       [25, 33, 23, 10],
       [16, 46, 49, 40]])>


### Getting information from tensors
1. Shape
2. Rank
3. Axis or dimension
3. Size

In [ ]:
rank_4_tensor = tf.ones(shape = (2,6,2,6))
rank_4_tensor

In [ ]:
rank_4_tensor[0][2]

In [ ]:
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

In [41]:
rank_4_tensor[:1,:2,:2,:2]
rank_4_tensor

<tf.Tensor: shape=(2, 6, 2, 6), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]]], dtype=float32)>

In [42]:
import numpy as np

In [44]:
basic_numpy = np.random.randint(1,100,24)
basic_numpy

array([33, 28, 25, 38, 96, 14, 79, 58, 20, 54, 45, 39, 94,  8, 45, 85, 17,
       24, 79, 72, 55, 45, 90, 21])

In [49]:
reshaped_numpy = basic_numpy.reshape(3,2,4)
reshaped_numpy

array([[[33, 28, 25, 38],
        [96, 14, 79, 58]],

       [[20, 54, 45, 39],
        [94,  8, 45, 85]],

       [[17, 24, 79, 72],
        [55, 45, 90, 21]]])

In [52]:
print(reshaped_numpy.base is basic_numpy)

True


In [73]:
new_nump = reshaped_numpy[0][0:2]
print(new_nump[0:2][1:])
print(new_nump[1][:2])

[[96 14 79 58]]
[96 14]


In [89]:
reshaped_numpy[0:2,0:1,1]

array([[28],
       [54]])

In [93]:
reshaped_numpy[:,:,1:4]

array([[[28, 25, 38],
        [14, 79, 58]],

       [[54, 45, 39],
        [ 8, 45, 85]],

       [[24, 79, 72],
        [45, 90, 21]]])

In [ ]:
# MATRIX MULTIPLICATION