<a href="https://colab.research.google.com/github/notjayasurya/DeepLearning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Fundamental concepts of tensors**

In [3]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [4]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
#Checking the no of dimensions of a tensor
scalar.ndim

0

In [7]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
vector.ndim

1

In [11]:
matrix = tf.constant([[24,48],[18,7]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[24 48]
 [18  7]], shape=(2, 2), dtype=int32)
2


In [19]:
#Creating another matrix
another_matrix = tf.constant([[10.,8.],
                             [1.,9.],
                             [10.,24.]],dtype=tf.float64)
print(another_matrix)
print(another_matrix.ndim)

tf.Tensor(
[[10.  8.]
 [ 1.  9.]
 [10. 24.]], shape=(3, 2), dtype=float64)
2


What we've created so far:
Scalar : a single number
vector : number with direction
matrix: a 2d array of numbers
Tensors : An n dim array of numbers .


### Creating tensors with 'tf.Variable'

In [24]:
changeable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changeable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [26]:
changable_tensor[0].assign(18)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([18,  7], dtype=int32)>

In [27]:
# Creating Random tensors : Playback = 1:22:42