<a href="https://colab.research.google.com/github/notjayasurya/DeepLearning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Fundamental concepts of tensors**

In [25]:
import tensorflow as tf

import numpy as np
print(tf.__version__)

2.5.0


In [ ]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Checking the no of dimensions of a tensor
scalar.ndim

0

In [ ]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[24,48],[18,7]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[24 48]
 [18  7]], shape=(2, 2), dtype=int32)
2


In [ ]:
#Creating another matrix
another_matrix = tf.constant([[10.,8.],
                             [1.,9.],
                             [10.,24.]],dtype=tf.float64)
print(another_matrix)
print(another_matrix.ndim)

tf.Tensor(
[[10.  8.]
 [ 1.  9.]
 [10. 24.]], shape=(3, 2), dtype=float64)
2


What we've created so far:
Scalar : a single number
vector : number with direction
matrix: a 2d array of numbers
Tensors : An n dim array of numbers .


### Creating tensors with 'tf.Variable'

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changeable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changable_tensor[0].assign(18)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([18,  7], dtype=int32)>

In [ ]:
# Creating Random tensors : Playback = 1:22:42

In [10]:
random_1 = tf.random.Generator.from_seed(36)
random_1 = random_1.normal(shape=(2,4))

random_2 = tf.random.Generator.from_seed(36)
random_2 = random_2.normal(shape = (2,4))

random_1,random_2, random_1 == random_2


(<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[-0.645002  ,  0.18022095, -0.14656258,  0.34374258],
        [ 0.41367555,  0.17573498, -1.0871261 ,  0.45905176]],
       dtype=float32)>, <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[-0.645002  ,  0.18022095, -0.14656258,  0.34374258],
        [ 0.41367555,  0.17573498, -1.0871261 ,  0.45905176]],
       dtype=float32)>, <tf.Tensor: shape=(2, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True]])>)

In [11]:
# Shuffling the order of tensors (valuable for shuffling the data)

In [19]:
not_shuffled = tf.constant([[10,7],
                            [24,7],
                           [18,45]],dtype=tf.int64)
print(not_shuffled.ndim)
not_shuffled

2


<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[10,  7],
       [24,  7],
       [18, 45]])>

In [21]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[18, 45],
       [10,  7],
       [24,  7]])>

In [24]:
tf.ones([4,8], dtype=tf.int32)

<tf.Tensor: shape=(4, 8), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>

In [26]:
#Converting numpy arrays into tensors

numpy_array = np.random.randint(10,50,20)
numpy_array


array([29, 13, 45, 22, 48, 36, 28, 32, 39, 46, 47, 19, 28, 43, 24, 10, 19,
       36, 16, 42])

In [32]:
A = tf.constant(numpy_array,shape =(5,4))
A

<tf.Tensor: shape=(5, 4), dtype=int64, numpy=
array([[29, 13, 45, 22],
       [48, 36, 28, 32],
       [39, 46, 47, 19],
       [28, 43, 24, 10],
       [19, 36, 16, 42]])>

In [ ]:
1:54:00